version: '3.8'

services:

  backend:
    build:
      context: ./ngo_api
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./ngo_api:/app
      - ./ngo_api/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 


  frontend:
    build:
      context: ./ngo_front
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./ngo_front:/app
    ports:
      - "3000:80"

volumes:
  db-data:
