# Generated by Django 5.1.1 on 2024-09-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('bio', models.TextField(max_length=5000)),
                ('localization', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('web', models.URLField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=255)),
                ('voivodeship', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('krs', models.CharField(max_length=20)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.categoryproject')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aim', models.TextField()),
                ('budget', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True)),
                ('conditions', models.TextField()),
                ('budget', models.CharField(max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('bio', models.TextField(blank=True, max_length=10000)),
                ('localization', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('web', models.URLField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=255)),
                ('voivodeship', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('krs', models.CharField(blank=True, max_length=20)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.categoryorganization')),
                ('partnership', models.ManyToManyField(related_name='ngos', to='api.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='partnership',
            field=models.ManyToManyField(related_name='partners', to='api.ngo'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=5000)),
                ('found', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('raport', models.TextField(blank=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.categoryproject')),
                ('company', models.ManyToManyField(blank=True, related_name='projects', to='api.company')),
                ('ngo', models.ManyToManyField(related_name='projects', to='api.ngo')),
            ],
        ),
    ]
