# Generated by Django 5.1.1 on 2024-09-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='partnership',
            field=models.ManyToManyField(blank=True, related_name='ngos', to='api.company'),
        ),
    ]
